stages:
  - build
  - deploy

build_job:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - master

deploy_job:
  stage: deploy
  image: microsoft/azure-cli
  script:
    - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
    - az webapp up --name <your-app-name> --resource-group <your-resource-group> --location <your-location> --html
  only:
    - master
