stages:
  - deploy
  - build
build_job:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - master

deploy_to_azure:
  stage: deploy
  image: linuxserver/openssh-server
  before_script:
  - chmod 400 $SSH_KEY

  script:
    - ssh  -o StrictHostKeyChecking=no -i $SSH_KEY $SERVER_USER@$SERVER_IP "rm -rf /tmp/my-react-app"
   
    - scp -o StrictHostKeyChecking=no -i $SSH_KEY -r ./* $SERVER_USER@$SERVER_IP:/tmp/my-react-app
    - ssh  -o StrictHostKeyChecking=no -i $SSH_KEY $SERVER_USER@$SERVER_IP "cd /tmp/my-react-app && npm install "
    - ssh  -o StrictHostKeyChecking=no -i $SSH_KEY $SERVER_USER@$SERVER_IP "cd /tmp/my-react-app && npm run start"

  environment:
    name: production
  only:
    - master