stages:
  - build
  - deploy

build_job:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - master

deploy_job:
  stage: deploy
  image: alpine:latest
  script:
    - scp -r build/* "workshopdevops"@Adnenhamdi2009":/tmp
    - ssh "workshopdevops"@Adnenhamdi2009" 'cd /tmp && ls'
  only:
    - master
