stages:
  - deploy
  - build
build_job:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - master

deploy_to_azure:
  stage: deploy
  image: linuxserver/openssh-server
  before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -

  script:
    - scp -o StrictHostKeyChecking=no -r ./* $SERVER_USER@$SERVER_IP:/tmp/my-react-app
    - ssh  -i $SSH_KEY $SERVER_USER@$SERVER_IP "cd /tmp/my-react-app && npm install && npm run start"
  environment:
    name: production
  only:
    - master