stages:
  - build
  - dockerize
  - deploy

build_job:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - master

dockerize_image:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t aminehamdi2001/devopsworkshop:1 .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push aminehamdi2001/devopsworkshop:1
  only:
    - master

deploy_to_azure:
  stage: deploy
  image: linuxserver/openssh-server
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $SERVER_USER@$SERVER_IP "docker pull aminehamdi2001/devopsworkshop:1 && docker run -d aminehamdi2001/devopsworkshop:1"
  only:
    - master
